/*
 * pcb13.h
 * IO Mappings for BrewMonitor PCB version 1.3
 * Created: 29/05/2014 9:40:58 AM
 *  Author: Michael
 */ 

#ifndef PCB13_H_
#define PCB13_H_

// Define IO
#define RECORD_LED_PORT PORTB
#define RECORD_LED_PIN PIN5
#define RECORD_LED_DDR DDRB

#define RECORD_BUTTON_INPORT PINB
#define RECORD_BUTTON_PIN PIN7
#define RECORD_BUTTON_DDR DDRB

#define BUBBLE_SENSOR_INPORT PINF
#define BUBBLE_SENSOR_DDR DDRF
#define BUBBLE_SENSOR_PIN PIN1

#define BUBBLE_SENSOR_PULLUP_PORT PORTF
#define BUBBLE_SENSOR_PULLUP_PIN PIN4
#define BUBBLE_SENSOR_PULLUP_DDR DDRF

#define BUBBLE_IR_LED_PORT PORTF
#define BUBBLE_IR_LED_PIN PIN0
#define BUBBLE_IR_LED_DDR DDRF

#define BUBBLE_LED_PORT PORTB
#define BUBBLE_LED_PIN PIN4
#define BUBBLE_LED_DDR DDRB

#define ONEWIRE_DATA_PORT PORTF
#define ONEWIRE_DATA_INPORT PINF
#define ONEWIRE_DATA_PIN PIN6
#define ONEWIRE_DATA_DDR DDRF

#define ONEWIRE_POWER_DDR DDRF
#define ONEWIRE_POWER_PORT PORTF
#define ONEWIRE_POWER_INPORT PINF
#define ONEWIRE_POWER_PIN PIN5

#define ONEWIRE_PULLUP_PORT PORTF
#define ONEWIRE_PULLUP_INPORT PINF
#define ONEWIRE_PULLUP_PIN PIN7
#define ONEWIRE_PULLUP_DDR DDRF

#define EEPROM_WP_DDR DDRD
#define EEPROM_WP_PIN PIN4
#define EEPROM_SCL_DDR DDRD
#define EEPROM_SCL_PORT PORTD
#define EEPROM_SCL_PIN PIN0
#define EEPROM_SDA_DDR DDRD
#define EEPROM_SDA_PIN PIN1

#endif /* PCB13_H_ */